version = "0.3.2"

[scripts]
build = [
  "git stash",
  "git pull",
  "docker build -t portable-dev-env ."
]
run.cmd = "docker run -it --name pde portable-dev-env -v /var/run/docker.sock:/var/run/docker.sock /bin/zsh "
rebuild.cmd = [
  "docker rm pde",
  "git stash",
  "git pull",
  "bonnie build",
  "bonnie run"
]
